### ISSUE TITLE
if else if else else

### ISSUE THREAD

**Issue by ljcordero** [Asabeneh/30DaysOfJavaScript#35]
Actually on day 4, there are some titles and paragraphs, making references to: "if else if else else"

https://github.com/Asabeneh/30DaysOfJavaScript/blob/master/04_Day/04_day_conditionals.md#if-else-if-else-else

I think the meaning of this title would be something like: " if else if else" without the extra "else" at the end.

But don't really like how its look, I preferrer something like: "If else and else if" or just "else if".

So I propose changing this title for one of these two options:

1. if else and else if
2. else if

Please comment your suggestions.

**Comment by ljcordero** [comment]
@nyan-lin-tun what may you help us here.

**Comment by nyan-lin-tun** [comment]
@ljcordero ok I will update the readme of Day4.
