### ISSUE TITLE
About translation!

### ISSUE THREAD

**Issue by ChuanErbao** [Asabeneh/30DaysOfJavaScript#55]
Hello!
Thank you for your help!
I'd like to create a new repo to translate this repo to Chinese?Would you like to give me the allowance？

Best  wishes!

**Comment by Asabeneh** [comment]
No, I would like to change the Repo to book. After I change it too book
shall we talk about it?

Thank you for your interest

**Comment by ChuanErbao** [comment]
My  pleasure!
