### ISSUE TITLE
Undeclared variable in Day 1

### ISSUE THREAD

**Issue by chriswilkinsoncodes** [Asabeneh/30DaysOfJavaScript#62]
Hi,

Thanks for this amazing resource!! It is really well put together and super easy to follow.

Unless I missed something along the way, the following console.log throws and error since age has not yet been declared:

![image](https://user-images.githubusercontent.com/51000551/72908158-1d0fea80-3d03-11ea-8626-9eb2e6ff6a0c.png)

Thanks again - I'm looking forward to working through the rest of the days!!

**Comment by Asabeneh** [comment]
Thanks. fixed
