### ISSUE TITLE
Day 2 - not showing output as expected

### ISSUE THREAD

**Issue by nomanaadma** [Asabeneh/30DaysOfJavaScript#83]
Hi,

Thanks for this amazing resource!! It is really well put together and super easy to follow.

Unless I missed something along the way, the following console.log not showing the output as expected in your resource.

The output i expected:
![expected-output](https://user-images.githubusercontent.com/47977013/79916658-8b6b6280-8442-11ea-8f22-f60fb2e6f12f.png)

The output i get:
![current-output](https://user-images.githubusercontent.com/47977013/79916684-96be8e00-8442-11ea-8461-bdfd726eeaab.png)

**Comment by Asabeneh** [comment]
Now it is fixed. Thanks

**Comment by Asabeneh** [comment]
Now it is fixed

**Comment by NimbleWing** [comment]
hi, it still unchange ！
